spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

messaging:
  provider: kafka
  kafka:
    enabled: true

outbox:
  scheduler:
    enabled: true

app:
  environment: development
