spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false

messaging:
  provider: none
  kafka:
    enabled: false

outbox:
  scheduler:
    enabled: false

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}

app:
  mail:
    sender: ${APP_MAIL_SENDER}
    recipient: ${APP_MAIL_RECIPIENT}
